name: resume_builder
description: A custom resume builder app using Flutter.

dependencies:
  file_picker: ^9.2.2
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  path: ^1.8.3

environment:
  sdk: ^3.6.0

flutter:
  uses-material-design: true
